name: "Publishing Package"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install --global yarn
      - run: yarn && yarn check
      - run: yarn test

  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org/
      - run: yarn --forzen-lockfile
      - run: yarn release
