name: "Build & Test Package"
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Get All branches
        run: |
          git fetch --no-tags
      # - name: Setup node
      #  uses: actions/setup-node@v1
      #  with:
      #    node-version: 10.x
      # - run: npm install --global yarn
      # - run: yarn
      - run: |
          git rev-list "origin/${{ github.head_ref }}".."origin/${{ github.base_ref }}" -2
      - run: |
          git log --oneline --decorate --abbrev-commit "origin/${{ github.base_ref }}".."origin/${{ github.head_ref }}"
      # - run: yarn test:ci
