name: "Build & Test Package"
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_EVENT: ${{ toJson(github.event) }}
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Get All branches
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: git checkout ${{ github.head_ref }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install --global yarn
      - run: yarn
      - run: git rev-list --simplify-by-decoration ${{ github.head_ref }}
      - run: git rev-list --simplify-by-decoration origin/${{ github.head_ref }}
      - run: yarn test:ci
